### PR TITLE
fix(1323): false positive in get-return rule for HTTP Get handlers

### LINKED ISSUE #1323: get-return: false positive in get-return rule for GetInfo HTTP handler
The rule `get-return` incorrectly flags the HTTP handler function [`GetInfo`](https://github.com/lima-vm/lima/blob/01b435a426ba6016e0d481d83a936cdc58b2be61/pkg/hostagent/api/server/server.go#L31) as a "getter", even though it doesn't return any values in the Go sense.

Diagnostic message:
```
get-return: function 'GetInfo' seems to be a getter but it does not return any result
```

Function:
```go
func (b *Backend) GetInfo(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.WriteHeader(http.StatusMethodNotAllowed)
		return
	}

	ctx := r.Context()
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	info, err := b.Agent.Info(ctx)
	if err != nil {
		b.onError(w, err, http.StatusInternalServerError)
		return
	}
	m, err := json.Marshal(info)
	if err != nil {
		b.onError(w, err, http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(m)
}
```

This function is an HTTP handler, and the fact that it is called `GetInfo` and uses `GET` does not mean it's a "getter" in the context of return values. The rule should be refined to avoid this false positive.

### PR DESCRIPTION
**Pull request by chavacava**
Closes #1323 by detecting HTTP hander signature.

### CODE REVIEW

File: internal/astutils/ast_utils.go [hunk 1]
```diff
@@ -15,28 +15,34 @@ func FuncSignatureIs(funcDecl *ast.FuncDecl, wantName string, wantParametersType
...
+		return false // func has not the expected number of parameters
+	}
+
+	for i, wantType := range wantParametersTypes {
+		if wantType != funcParametersTypes[i] {
+			return false // type of a func's parameter does not match the type of the corresponding expected parameter
+		}
+	}
+
 	return true
```
Comment (ccoVeille) [inline internal/astutils/ast_utils.go:46]: I had to read it multiple times to understand what you try to achieve.

Isn't simply about using Go std [slices.Equal](https://pkg.go.dev/slices#Equal) ?


```suggestion
	funcParametersTypes := getTypeNames(funcDecl.Type.Params)

 	return slices.Equal(wantParametersTypes, funcParametersTypes)
```

File: rule/get_return.go [hunk 2]
```diff
@@ -29,6 +30,10 @@ func (*GetReturnRule) Apply(file *lint.File, _ lint.Arguments) []lint.Failure {
 			continue
 		}
 
+		if astutils.FuncParametersSignatureIs(fd, []string{"http.ResponseWriter", "*http.Request"}) {
+			continue // the Get prefix in the function name refers to HTTP GET
+		}
```
Comment (ccoVeille) [inline rule/get_return.go:35]: While this matches what was reported by @alexandear 

I would have extended by using

```suggestion
		if slices.Contain( getTypeNames(fd.Type.Params), []string{"http.ResponseWriter", "*http.Request"}) {
			continue // the Get prefix in the function name refers to HTTP GET
		}
```

Comment (chavacava) [reply rule/get_return.go:35]: With that condition the rule will accept all get methods with `http.ResponseWriter` and `*http.Request` parameters regardless their order or how many other parameters in the method signature.
Is that what we want? Do you have examples?

Comment (ccoVeille) [reply rule/get_return.go:35]: You are right, slices.Contain does care about orders

Here are [examples](https://github.com/search?q=%2Ffunc%5Cs*%28%5C%28.*%5C%29%29%3F%5Cs*Get.*%5C%28.+http%5C.ResponseWriter%2C+.+%5C*http%5C.Request%2C.*%5C%29+%5C%7B%2F+path%3A*.go+language%3AGo&type=code&ref=advsearch) with extra parameters: 7.6k today

This is the pattern I met at work

[GetWhatever(w http.ResponseWriter, r *http.Request, p httprouter.Params) {](https://github.com/search?q=%2Ffunc%5Cs*%28%5C%28.*%5C%29%29%3F%5Cs*Get.*%5C%28.+http%5C.ResponseWriter%2C+.+%5C*http%5C.Request%2C+.+httprouter%5C.Params%5C%29+%5C%7B%2F+path%3A*.go+language%3AGo&type=code&ref=advsearch) 1.2k today

Comment (ccoVeille) [reply rule/get_return.go:35]: > With that condition the rule will accept all get methods with http.ResponseWriter and *http.Request parameters regardless their order or how many other parameters in the method signature.\nIs that what we want? 

I would say that any getter method/function that returns nothing and first two parameters are "http.ResponseWriter, *http.Request" in that order should be ignored, no matter the number of parameters (>=2)

**Review by denisvmedia — APPROVED** [review]
LGTM

**Review by ccoVeille — CHANGES_REQUESTED** [review]
If there is non-consensus on the feedback I did about [other possible signatures](https://github.com/mgechev/revive/pull/1325#discussion_r2061239105) that could also avoided, I'm fine with merging it with the current code that detect http.Handler signature

But because I would like to get a feedbackvon [this other comment](https://github.com/mgechev/revive/pull/1325#discussion_r2061207981), I will mark the PR as "changes required"

**Review by ccoVeille — APPROVED** [review]
Thanks

**Comment by chavacava** [comment]
@ccoVeille thanks for the feedback.

I've introduced some modifications to match your remarks:
1. Yes, `slices.Equals`  is the way to go
2. Any getter method/function that returns nothing and first two parameters are "http.ResponseWriter, *http.Request" in that order is ignored
