### PR TITLE
fix: cognitive complexity nesting with if-else chains

### LINKED ISSUE #1267: Cognitive complexity adds incorrect nesting for if-else chains
**Describe the bug**

Currently, an if-else chain will increase the nesting level and add the nesting increment for every addition `else if` statement in an if-else chain. This is incorrect behaviour; an `else if` statement should increment complexity by 1 (regardless of current nesting level) and leave the nesting level as-is.
    
For example, the following should yield a total complexity of 5:
```
    for { // +1
        if a { // +2 (nesting = 1)
            foo()
        } else if b { // +1
            bar()
        } else if c { // +1
            baz()
        }
    }
```
but the current implementation incorrectly increments the nesting level with each `else if` and adds the nesting increment where it shouldn't:
```
    for { // +1
        if a { // +2 (nesting = 1)
            foo()
        } else if b { // +3 (nesting = 2)
            bar()
        } else if c { // +4 (nesting = 3)
            baz()
        }
    }
```

### PR DESCRIPTION
**Pull request by AxiomaticFixedChimpanzee**
Fixes #1267

### CODE REVIEW

File: rule/cognitive_complexity.go [hunk 1]
```diff
@@ -156,6 +155,29 @@ func (v *cognitiveComplexityVisitor) walk(complexityIncrement int, targets ...as
 	v.nestingLevel = nesting
 }
 
+func (v *cognitiveComplexityVisitor) walkIfElse(n *ast.IfStmt) {
+	var w func(n *ast.IfStmt)
+	w = func(n *ast.IfStmt) {
```
Comment (chavacava) [inline rule/cognitive_complexity.go:160]:
```suggestion
	w := func(n *ast.IfStmt) {
```

File: rule/cognitive_complexity.go [hunk 2]
```diff
@@ -156,6 +155,29 @@ func (v *cognitiveComplexityVisitor) walk(complexityIncrement int, targets ...as
...
+		ast.Walk(v, n.Cond)
+		ast.Walk(v, n.Body)
+		if n.Else != nil {
+			if elif, ok := n.Else.(*ast.IfStmt); ok {
+				v.complexity += 1
```
Comment (ccoVeille) [inline rule/cognitive_complexity.go:165]:
```suggestion
				v.complexity++
```

File: testdata/cognitive_complexity.go [hunk 3]
```diff
@@ -291,3 +291,16 @@ func Walk(t *Tree, ch chan int) { // MATCH /function Walk has cognitive complexi
...
+	if a { // +1
+		foo()
+	} else if b && c { // +2
+		bar()
+	} else if d { // +1
+		baz()
+	} else {
+		qux()
+	}
+}
```
Comment (ccoVeille) [inline testdata/cognitive_complexity.go:306]:
```suggestion
// Test if-else if chains
func chainedIfElse(a, b, c, d bool) { // MATCH /function chainedIfElse has cognitive complexity 4 (> max enabled 0)/
	if a { // +1
		foo()
	} else if b && c { // +2
		bar()
	} else if d { // +1
		baz()
	} else {
		qux()
	}
}
```

File: rule/cognitive_complexity.go [hunk 4]
```diff
@@ -156,6 +155,29 @@ func (v *cognitiveComplexityVisitor) walk(complexityIncrement int, targets ...as
...
+				w(elif)
+			} else {
+				ast.Walk(v, n.Else)
+			}
+		}
+	}
+
+	// The nesting level is incremented within the if and else blocks, but the nesting increment is only added to the complexity
+	// for the first if in an if-else-if chain.
```
Comment (ccoVeille) [inline rule/cognitive_complexity.go:174]: I would like to suggest something like this

```suggestion
	// Nesting level is incremented in 'if' and 'else' blocks, but only the first 'if' in an 'if-else-if' chain sees its complexity increased by the nesting level."
```

**Review by ccoVeille — APPROVED** [review]
Nitpicking and a rewording suggestion

File: rule/cognitive_complexity.go (hunk 1 above)
Comment (AxiomaticFixedChimpanzee) [reply rule/cognitive_complexity.go:160]: The function is recursive, so must be declared first otherwise it won't compile.

**Review by ccoVeille — APPROVED** [review]
