### PR TITLE
fix: add-constant struct tags in anonymous struct literals false positive

### LINKED ISSUE #951: add-constant suggests invalid fix of replacing struct tags with string constants for anonymous structs
**Describe the bug**

revive incorrectly suggests replacing duplicated struct tags with string constants, for tags found in anonymous struct literals.

Example file to reproduce:

```
package test

func x() {
	a := struct {
		X int `json:"x"`
	}{}

	b := struct {
		X int `json:"x"`
	}{}

	c := struct {
		X int `json:"x"`
	}{}

	_, _, _ = a, b, c
}
```

**To Reproduce**
1. I updated revive `go install github.com/mgechev/revive@latest`
2. I run it with the following flags & configuration file:

```shell
# flags

revive -config config.toml .
```

Output:

```
test.go:13:9: string literal `json:"x"` appears, at least, 3 times, create a named constant for it
```

```toml
[rule.add-constant]
```

**Expected behavior**
Struct tags in anonymous struct literals should be ignored by this rule, as they are for struct type definitions.

### PR DESCRIPTION
**Pull request by denisvmedia**
closes #951

### CODE REVIEW

File: rule/add-constant.go [hunk 1]
```diff
@@ -171,6 +187,12 @@ func (w lintAddConstantRule) checkNumLit(kind string, n *ast.BasicLit) {
 	})
 }
 
+// isStructTag checks if the given BasicLit is part of a struct tag.
```
Comment (denisvmedia) [inline rule/add-constant.go:190]:
```suggestion
```
