### PR TITLE
fix(#1363): package-comments ignores //nolint directives

### LINKED ISSUE #1363: `package-comments` ignores `//nolint` directives
**Describe the bug**

**To Reproduce**
1. I updated revive `go install github.com/mgechev/revive@latest`
2. I run it with no flags or config file, on the following:

```
// myfile1.go
// Package mine does something
package mine

func doSomething() {}

// myfile2.go
//nolint:dupl
package mine

func doSomethingElse() {}
```

**Expected behavior**
No lint warnings, since the package does have a comment (in `myfile1.go`), and the other comment is a directive-type comment (specifically, it's for golangci-lint)

**Logs**

```
workspace/projects-scrap/package-comments-check via 🐹 v1.24.2 took 2s
❯ ./revive .
myfile2.go:1:1: package comment should be of the form "Package mine ..."
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, via WSLv2
 - Version of Go: v1.24

**Additional context**

From what I can find, it seems like directives are meant to be ignored (e.g. https://github.com/mgechev/revive/pull/989).

The situation I'm dealing with is that the `dupl` linter is flagging code that includes the `package` line meaning we have to put our `nolint` directively immediately before that (including without any newlines between it) - while it looks like I can include a `//nolint:revive` in between, the danger is that could mistakenly lead to disabling `revive` for the whole file as that'd happen if the line is merged (`//nolint:dupl,revive`) or if the `dupl` linter line is removed (e.g. because the code is changed and then the linter complains the directive is not doing anything anymore)

### PR DESCRIPTION
**Pull request by chavacava**
Closes #1363 

Root cause of the bug: when checking package comments, the rule doesn't skip directive-comments at the right place.

### CODE REVIEW

File: rule/package_comments.go [hunk 1]
```diff
@@ -162,3 +162,11 @@ func (l *lintPackageComments) Visit(_ ast.Node) ast.Visitor {
 	}
 	return nil
 }
+
+func isEmptyDoc(commentGroup *ast.CommentGroup) bool {
+	if commentGroup == nil {
```
Comment (ccoVeille) [inline rule/package_comments.go:167]: Don't we have something like that in exported?

Can we reuse the same code?

File: rule/package_comments.go [hunk 2]
```diff
@@ -143,7 +143,7 @@ func (l *lintPackageComments) Visit(_ ast.Node) ast.Visitor {
 		}
 	}
 
-	if l.fileAst.Doc == nil {
+	if isEmptyDoc(l.fileAst.Doc) {
 		for _, failure := range l.checkPackageComment() {
```
Comment (ccoVeille) [inline rule/package_comments.go:147]: Could you please add test?

File: rule/package_comments.go (hunk 1 above)
Comment (chavacava) [reply rule/package_comments.go:167]: I think so... I've didn't search for it.

File: revivelib/core.go [hunk 3]
```diff
@@ -169,7 +169,8 @@ func (r *Revive) Format(
 	return output, exitCode, nil
 }
 
-func getPackages(includePatterns []string, excludePatterns ArrayFlags) ([][]string, error) {
+// GetPackages yields the packages and corresponding files for the given patterns
+func GetPackages(includePatterns []string, excludePatterns ArrayFlags) ([][]string, error) {
```
Comment (ccoVeille) [inline revivelib/core.go:173]: Could me move this to internal, so it's not used outside the module?

**Review by ccoVeille — COMMENTED** [review]
That's a lot of changes 😱

File: revivelib/core.go (hunk 3 above)
Comment (chavacava) [reply revivelib/core.go:173]: yes, I'm undoing the "let's use patterns in tests" path

**Comment by chavacava** [comment]
> That's a lot of changes 😱

Yes... I think I hit a bug in `dots.Resolve` when it runs on Windows. I don´t have a windows machine so... I tried to catch the bug by relying on the GH CI...

**Review by ccoVeille — APPROVED** [review]
I would say OK, but I cannot swear I reviewed everything

**Comment by chavacava** [comment]
> I would say OK, but I cannot swear I reviewed everything

Thanks! The PR seems "complicated" but it does very few things:
1. Fix #1363 by checking if the block comment attached to package declaration is not "empty" (after removing empty lines and directives)
2. Add a test case: the very same of #1363 
3. Add a new helper method in test utils to test a rule _against a list of files_ (vs the usual _against a single file_): this is where it seems to be a lot of changes but it's just the original helper functions with some extra `for-range` to iterate over the list of files. (easier to read with a side-by-side diff or by directly reading the final file)

**Comment by ccoVeille** [comment]
Thanks for the details, I assumed it was something like that, yes

If you plan to squash your commits into one, what you wrote could be used as a good commit message

File: test/package_comments_issue1363_test.go [hunk 4]
```diff
@@ -0,0 +1,17 @@
+package test
```
Comment (alexandear) [inline test/package_comments_issue1363_test.go:1]: 1. Tests for `package-comments` is inside the `testdata/golint` directory.
2. I assume we can add simply `testdata/golint/package_doc7.go` instead of modifying test suite:
```go
//nolint:dupl
package foo
```

Before the fix:

```console
$ go test ./...
?       github.com/mgechev/revive       [no test files]
ok      github.com/mgechev/revive/cli   0.504s
ok      github.com/mgechev/revive/config        1.181s
ok      github.com/mgechev/revive/formatter     0.855s
?       github.com/mgechev/revive/internal/astutils     [no test files]
?       github.com/mgechev/revive/internal/ifelse       [no test files]
?       github.com/mgechev/revive/internal/typeparams   [no test files]
ok      github.com/mgechev/revive/lint  0.674s
ok      github.com/mgechev/revive/logging       0.315s
ok      github.com/mgechev/revive/revivelib     1.050s
ok      github.com/mgechev/revive/rule  1.498s
--- FAIL: TestAll (0.90s)
    --- FAIL: TestAll/package_doc7.go (0.00s)
        golint_test.go:71: Unexpected problem at package_doc7.go:1: package comment should be of the form "Package foo ..."
FAIL
FAIL    github.com/mgechev/revive/test  2.314s
FAIL
```

After applying the fix:

```console
$ go test ./...
?       github.com/mgechev/revive       [no test files]
ok      github.com/mgechev/revive/cli   (cached)
ok      github.com/mgechev/revive/config        (cached)
ok      github.com/mgechev/revive/formatter     (cached)
?       github.com/mgechev/revive/internal/astutils     [no test files]
?       github.com/mgechev/revive/internal/ifelse       [no test files]
?       github.com/mgechev/revive/internal/typeparams   [no test files]
ok      github.com/mgechev/revive/lint  (cached)
ok      github.com/mgechev/revive/logging       (cached)
ok      github.com/mgechev/revive/revivelib     0.326s
ok      github.com/mgechev/revive/rule  (cached)
ok      github.com/mgechev/revive/test  1.407s
```

See my example in #1371
