### PR TITLE
fix duplicated findings for string-format when there is more than one…

### LINKED ISSUE #1063: Duplicated findings for `string-format` when there is more than one scope provided for single argument
**Describe the bug**
For `string-format` rule, when there is more than one scope provided for single argument there are duplicated findings in the results.
The number of findings is the same as the number of scopes provided in the configuration.

**To Reproduce**
1. I updated revive `go install github.com/mgechev/revive@latest`
2. I run it with the following flags & configuration file:

```shell
# flags
revive -config revive.toml msg.go
```

```toml
# config file
[rule.string-format]
    arguments = [
        ["fmt.Errorf[0],errors.New[0]", "/^([^A-Z]|$)/", "must not start with a capital letter"],
    ]
```

`msg.go`:
```go
package main

import (
	"errors"
)

func ReturnError() error {
	return errors.New("This is an error.")
}
```

**Expected behavior**
A single finding is found.

**Expected behavior**
Two findings are there:
```
msg.go:8:20: must not start with a capital letter
msg.go:8:20: must not start with a capital letter
```

**Desktop (please complete the following information):**
 - OS: `Ubuntu 23.10`
 - Version of Go: `1.23.0`

### PR DESCRIPTION
**Pull request by chavacava**
Closes #1063 + minor code refactoring

### CODE REVIEW

File: rule/string-format.go [hunk 1]
```diff
@@ -216,7 +216,7 @@ func (w lintStringFormatRule) Visit(node ast.Node) ast.Visitor {
 	for _, rule := range w.rules {
 		for _, scope := range rule.scopes {
 			if scope.funcName == callName {
-				rule.Apply(call)
+				rule.apply(call,scope)
```
Comment (alexandear) [inline rule/string-format.go:219]:
```suggestion
				rule.apply(call, scope)
```

File: rule/string-format.go [hunk 2]
```diff
@@ -251,81 +251,73 @@ func (lintStringFormatRule) getCallName(call *ast.CallExpr) (callName string, ok
...
-		return
+	r.generateFailure(unquoted, lit)
+}
+
+func (r *stringFormatSubrule) stringIsOK(s string) bool {
+	matches := r.regexp.MatchString(s)
+	if r.negated {
+		return !matches
 	}
+
```
Comment (alexandear) [inline rule/string-format.go:306]: Redundant TAB, can be removed:
```suggestion

```

**Review by alexandear — CHANGES_REQUESTED** [review]
Please run `gofmt -w rule/string-format.go` to fix comments that I left.

File: rule/string-format.go
Comment (alexandear) [inline rule/string-format.go:1]: I'm suggesting to add the test to verify the issue is really fixed.

`test/string-format_test.go`:

```go
func TestStringFormatDuplicatedStrings(t *testing.T) {
	testRule(t, "string-format-issue-1063", &rule.StringFormatRule{}, &lint.RuleConfig{
		Arguments: lint.Arguments{[]any{
			"fmt.Errorf[0],errors.New[0]",
			"/^([^A-Z]|$)/",
			"must not start with a capital letter",
		}},
	})
}
```


`testdata/string-format-issue-1063.go`:

```go
package fixtures

import (
	"errors"
)

func ReturnError() error {
	return errors.New("This is an error.") // MATCH /must not start with a capital letter/
}
```

**Review by alexandear — APPROVED** [review]
