### PR TITLE
package-directory-mismatch: allow test package names in version paths

### LINKED ISSUE #1542: package-directory-mismatch false positive for package under version folder
**Describe the bug**
I have a version a test package `manifest_test` in  factoid/pkg/apis/manifest/v1, revive gives back

```
factoid/pkg/apis/manifest/v1/fact_test.go:1:9: package-directory-mismatch: package name "manifest_test" does not match directory name "v1" or parent directory name "manifest" (revive) package manifest_test
```
However, manifest is a part of manifest_test.

This works fine for non-test code in the package `manifest`, but not the test code.

**To Reproduce**
Create a folder like
foo/v1/foo_test.go
foo/v1/foo.go
where foo is in `package foo` and foo_test is in `package foo_test`, then foo_test will fail revive.

**Expected behavior**

revive should allow package foo_test when it's under `foo/v1`

**Logs**
Image

**Additional context**

### PR DESCRIPTION
**Pull request by thespags**
Added test case following the other `PackageDirectoryMismatchRule` tests.

Closes #1542.

### CODE REVIEW

File: rule/package_directory_mismatch.go [hunk 1]
```diff
@@ -137,6 +137,13 @@ func (r *PackageDirectoryMismatchRule) Apply(file *lint.File, _ lint.Arguments)
 			return nil
 		}
 
+		if file.IsTest() {
```
Comment (thespags) [inline rule/package_directory_mismatch.go:140]: We could refactor this block to avoid having checks missed, but I was worried about following the coding styles

File: .gitignore [hunk 2]
```diff
@@ -4,3 +4,4 @@ vendor
 *.swp
 dist/
 *.log
+.idea/
```
Comment (thespags) [inline .gitignore]: Follow intellij/goland users.

Comment (chavacava) [reply .gitignore]: Please remove this file from the PR.
https://tekin.co.uk/2020/03/maintain-a-global-git-ignore-file

**Comment by thespags** [comment]
Hi @alexandear , can I get help debugging why the file isn't appearing in CI? 
> Error:     package_directory_mismatch_test.go:40: Bad filename path in test for package-directory-mismatch: open ../testdata/package_directory_mismatch/api/v1/api_test.go: no such file or directory

**Comment by alexandear** [comment]
> Hi @alexandear , can I get help debugging why the file isn't appearing in CI?
> 
> > Error:     package_directory_mismatch_test.go:40: Bad filename path in test for package-directory-mismatch: open ../testdata/package_directory_mismatch/api/v1/api_test.go: no such file or directory

You need to rename the `V1` directory to `v1`. Ubuntu is a case-sensitive OS.

image

**Comment by thespags** [comment]
Thanks @alexandear, I'm following the other test which has a case for v1 and V1
```
testRule(t, "package_directory_mismatch/api/v1/api", &rule.PackageDirectoryMismatchRule{}, config)
```

**Review by alexandear — APPROVED** [review]

**Comment by thespags** [comment]
Who's someone that can merge @alexandear? Thanks.

**Comment by thespags** [comment]
@uloamaka do you have access to merge this?

**Comment by alexandear** [comment]
@thespags I'll merge the PR tomorrow if @chavacava or @denisvmedia don't review it. Thanks for your patience.

**Comment by chavacava** [comment]
Thank you @thespags for the PR and @alexandear for the reviews and feedback

**Comment by thespags** [comment]
Thank you!
