### PR TITLE
fixes issue #280

### LINKED ISSUE #280: Bare return detected in an anynomous function inside a function only if the latter function’s return value is named
**Describe the bug**
With `[rule.bare-return]` on, Revive emits an error message in the case detailed below, and not in another case, also detailed below, that I think should be equivalent.

**To Reproduce**
1. I updated revive `go get -u github.com/mgechev/revive`
2. I run it with the following flags & configuration file:

```shell
# flags

revive ...
```

```toml
[rule.bare-return]
```

**Expected behavior**
No output.

**Logs**
`main.go:5:3: avoid using bare returns, please add return expressions`

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2 (based on Ubuntu 18.04)
 - Version of Go: 1.13.4

**Additional context**

Here is the minimum example that triggers the Revive error:
```go
package main

func f() (err error) {
	func() {
		return
	}()

	return nil
}
```

No errors are produced if the return value is not named:
```go
package main

func f() error {
	func() {
		return
	}()

	return nil
}
```

I think there should be no difference between the two cases, since the incriminated `return` is in an anonymous function that is identical in both cases.

### PR DESCRIPTION
**Pull request by chavacava**
Closes #280

### CODE REVIEW

File: fixtures/bare-return.go [hunk 1]
```diff
@@ -31,3 +31,38 @@ func bare4(a string, b int) string {
 func bare5(a string, b int) {
 	return
 }
+
+// NR tests for issue #280
+func f280_1() (err error) {
+	func() {
+		return
```
Comment (mgechev) [inline fixtures/bare-return.go]: I'm missing something here. Why we don't report an error?

Comment (chavacava) [reply fixtures/bare-return.go]: A _bare return_ is a `return` that makes _implicit_ reference to the _named_ return values of the function 
The scope of the `return` at line 38 is the function literal. That func literal does not have return values thus the `return` it is not a bare return
